env:
  - GO111MODULE=on
  - CGO_ENABLED=0

builds:
  - binary: niltalk
    main: ./
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X "main.buildString={{ .Tag }} ({{ .ShortCommit }} {{ .Date }})" -X "main.versionString={{ .Tag }}"

    hooks:
      # stuff executables with static assets.
      post: make pack-bin BIN={{ .Path }}

archives:
  - format: tar.gz
    files:
      - README.md
      - LICENSE

dockers:
  -
    goos: linux
    goarch: amd64
    goarm: ''
    binaries:
    - niltalk
    image_templates:
    - "kailashnadh/niltalk:latest"
    - "kailashnadh/niltalk:{{ .Tag }}"
    skip_push: false
    dockerfile: Dockerfile
    extra_files:
    - config.toml.sample
